### ISSUE TITLE
orthogonal loss

### ISSUE THREAD

**Issue by DawnJYe** [TL-UESTC/UniMoS#2]
The difference loss in 《Domain Separation Networks》 is the Frobenius norm of a matrix composed of vectors, where the elements of the matrix are the dot products of these vectors. A smaller value indicates lower similarity between the vectors, which I understand. However, in your paper, you mention calculating the Frobenius norm of a matrix obtained by multiplying two vectors, where the matrix elements are products of the vector components. This seems unrelated to vector similarity. What is the significance of this?

**Comment by xinyao326** [comment]
Thanks for your interest. The major difference between Domain Separation Networks and our paper is that we only calculate vector similarities between the vision and text feature of THE SAME SAMPLE, rather than any two sample as in Domain Separation Networks. We perform dot products to get similarites as in Domain Separation Networks. We updated the implementation for better alignment with the paper.

**Comment by DawnJYe** [comment]
Calculating similarity using the dot product results in a real number. Why do you apply the Frobenius norm to it? As I understand it, the Frobenius norm is typically used for matrices.

**Comment by xinyao326** [comment]
Calulating similarities between two batches of features with shape (B, D) results in a similarity matrix of shape (B,1), on which the frobenius norm is adopted.

**Comment by DawnJYe** [comment]
In your paper, you mention in Equation 3 that the text features and image features are both dv-dimensional and are single vectors, not involving a batch. The result of the dot product of the two vectors is a real number. Did I misunderstand?

**Comment by xinyao326** [comment]
In the paper, for better clarity and, without loss of generality, we discuss on single vectors, which can be viewed as a special case where batch size is 1. In implementation, the features are batched with B>1.

**Comment by DawnJYe** [comment]
Oh, I understand now, thank you. If you write it in the same format as the 'Domain Separation Networks' paper, it would be very clear and straightforward.

**Comment by xinyao326** [comment]
Thank you for your advice and interest in the paper.

**Comment by DawnJYe** [comment]
I also have a question regarding Equation 13 in your paper. Why is there a negative sign in front of the mean vector?
